author: "dterletskiy"
version: "1.1.0"
umbs_min_version: "0.1"

include: "variables.yaml"



variables:
  DIRECTORIES:
    ROOT: "/mnt/docker/builder_arm64v8_ubuntu_22.04/build"
    SOURCE: ${DIRECTORIES.ROOT}/source/
    BUILD: ${DIRECTORIES.ROOT}/build/
    DEPLOY: ${DIRECTORIES.ROOT}/deploy/
    TEST: ${DIRECTORIES.ROOT}/_____/${DIRECTORIES.SOURCE}/_____/${DIRECTORIES.BUILD}/_____/${DIRECTORIES.DEPLOY}/
  XEN:
    SOURCE:
      GITHUB:
        URL: "https://github.com/xen-project/xen.git"
        BRANCH: "RELEASE-4.16.2"
    CONFIG:
      ARM: defconfig
      ARM64: defconfig
      X86: qemu-defconfig
      X86_64: qemu-defconfig
  UBOOT:
    SOURCE:
      GITHUB:
        URL: "https://github.com/u-boot/u-boot.git"
        BRANCH: "v2022.07"
    CONFIG:
      ARM: umbs_qemu_arm_defconfig
      ARM64: umbs_qemu_arm64_defconfig
      X86: umbs_qemu-x86_defconfig
      X86_64: umbs_qemu-x86_64_defconfig
  BUSYBOX:
    SOURCE:
      GITHUB:
        URL: "https://github.com/mirror/busybox.git"
        BRANCH: "1_36_0"
    CONFIG:
      ARM: umbs_defconfig
      ARM64: umbs_defconfig
      X86: umbs_defconfig
      X86_64: umbs_defconfig
  BUILDROOT:
    SOURCE:
      GITHUB:
        URL: "https://github.com/buildroot/buildroot.git"
        BRANCH: "2023.02"
    CONFIG:
      ARM: umbs_qemu_arm_vexpress_defconfig
      ARM64: umbs_qemu_aarch64_virt_defconfig
      X86: umbs_qemu_x86_defconfig
      X86_64: umbs_qemu_x86_64_defconfig
  KERNEL:
    SOURCE:
      GITHUB:
        URL: "https://github.com/torvalds/linux.git"
        BRANCH: "v6.2"
    CONFIG:
      ARM: vexpress_defconfig
      ARM64: defconfig
      X86: x86_64_defconfig
      X86_64: x86_64_defconfig
  ANDROID:
    UBOOT:
      SOURCE:
        GITHUB:
          URL: "https://github.com/dterletskiy/aosp_manifest.git"
          BRANCH: "u-boot/manifest/u-boot-mainline-9671786"
      CONFIG:
        ARM64: "//u-boot:qemu_aarch64"
    KERNEL:
      SOURCE:
        GITHUB:
          URL: "https://github.com/dterletskiy/aosp_manifest.git"
          BRANCH: "kernel/manifest/common-android14-6.1-dev"
      CONFIG:
        ARM64: "//common-modules/virtual-device:virtual_device_aarch64"



projects:
  config:
    active: true
    dir: lfs
    sources:
      - type: git
        url: "git@github.com:dterletskiy/linux_from_scratch.git"

  xen:
    active: true
    dir: xen
    sources:
      - type: git
        url: ${XEN.SOURCE.GITHUB.URL}
        branch: ${XEN.SOURCE.GITHUB.BRANCH}
    builders:
      - type: make.xen
        defconfig: ${XEN.CONFIG.ARM64}
        arch: "arm64"
        compiler: "aarch64-linux-gnu-"
        jobs: 4
        targets:
          - "dist-xen"
          - "dist-doc"
        env:
          - ""
        artifacts:
          - "dist/install/boot/xen"
        deps:
          - ""

  u-boot:
    active: true
    dir: loader/u-boot
    sources:
      - type: git
        url: ${UBOOT.SOURCE.GITHUB.URL}
        branch: ${UBOOT.SOURCE.GITHUB.BRANCH}
    patches:
      - type: copy
        content:
          - from: "lfs/configuration/config/u-boot/v2022.07/qemu_arm64_defconfig/exp/defconfig"
            to: "configs/${UBOOT.CONFIG.ARM64}"
    builders:
      - type: make.uboot
        defconfig: ${UBOOT.CONFIG.ARM64}
        arch: "arm64"
        compiler: "aarch64-linux-gnu-"
        jobs: 4
        env:
          - ""
        artifacts:
          - "u-boot"
          - "u-boot.bin"
          - "scripts/dtc/dtc"
          - "tools/dumpimage"
          - "tools/fit_info"
          - "tools/mkenvimage"
          - "tools/mkimage"
          - "tools/img2srec"
        deps:
          - ""

  busybox:
    active: true
    dir: linux/busybox
    sources:
      - type: git
        url: ${BUSYBOX.SOURCE.GITHUB.URL}
        branch: ${BUSYBOX.SOURCE.GITHUB.BRANCH}
    patches:
      - type: copy
        content:
          - from: "lfs/configuration/config/busybox/1.35.0/arm64/exp/.config"
            to: "configs/${BUSYBOX.CONFIG.ARM64}"
    builders:
      - type: make.busybox
        defconfig: ${BUSYBOX.CONFIG.ARM64}
        arch: "arm64"
        compiler: "aarch64-linux-gnu-"
        jobs: 4
        env:
          - ""
        artifacts:
          - "_install"
        deps:
          - ""

  buildroot:
    active: true
    dir: linux/buildroot
    sources:
      - type: git
        url: ${BUILDROOT.SOURCE.GITHUB.URL}
        branch: ${BUILDROOT.SOURCE.GITHUB.BRANCH}
    patches:
      - type: copy
        content:
          - from: "lfs/configuration/config/buildroot/2022.05.2/qemu_aarch64_virt_defconfig/exp/defconfig"
            to: "configs/${BUILDROOT.CONFIG.ARM64}"
    builders:
      - type: make.buildroot
        defconfig: ${BUILDROOT.CONFIG.ARM64}
        arch: "arm64"
        compiler: "aarch64-linux-gnu-"
        jobs: 4
        env:
          - ""
        artifacts:
          - "output/images/rootfs.cpio"
          - "output/images/rootfs.ext2"
        deps:
          - ""

  kernel:
    active: true
    dir: linux/kernel
    sources:
      - type: git
        url: ${KERNEL.SOURCE.GITHUB.URL}
        branch: ${KERNEL.SOURCE.GITHUB.BRANCH}
    builders:
      - type: make.kernel
        defconfig: ${KERNEL.CONFIG.ARM64}
        arch: "arm64"
        compiler: "aarch64-linux-gnu-"
        jobs: 4
        env:
          - ""
        artifacts:
          - "arch/arm64/boot/Image"
          - "arch/arm64/boot/Image.gz"
        deps:
          - ""

  android-u-boot:
    active: true
    dir: android/u-boot
    sources:
      - type: repo
        manifest-url: ${ANDROID.UBOOT.SOURCE.GITHUB.URL}
        manifest-branch: ${ANDROID.UBOOT.SOURCE.GITHUB.BRANCH}
        manifest-name: "default.xml"
    builders:
      - type: android.uboot
        config: ${ANDROID.UBOOT.CONFIG.ARM64}
        env:
          - ""
        artifacts:
          - "out/deploy/${ANDROID.UBOOT.CONFIG.ARM64}/u-boot"
          - "out/deploy/${ANDROID.UBOOT.CONFIG.ARM64}/u-boot.bin"
        deps:
          - ""

  android-kernel:
    active: true
    dir: android/kernel
    sources:
      - type: repo
        manifest-url: ${ANDROID.KERNEL.SOURCE.GITHUB.URL}
        manifest-branch: ${ANDROID.KERNEL.SOURCE.GITHUB.BRANCH}
        manifest-name: "default.xml"
    builders:
      - type: android.kernel
        config: ${ANDROID.KERNEL.CONFIG.ARM64}
        env:
          - ""
        artifacts:
          - "out/deploy/${ANDROID.KERNEL.CONFIG.ARM64}/boot.img"
          - "out/deploy/${ANDROID.KERNEL.CONFIG.ARM64}/Image"
          - "out/deploy/${ANDROID.KERNEL.CONFIG.ARM64}/initramfs.img"
          - "out/deploy/${ANDROID.KERNEL.CONFIG.ARM64}/vmlinux"
        deps:
          - ""

  boot:
    active: true
    dir: images
    patches:
      - type: mkscr
        source: "lfs/configuration/scripts/boot.scr/main.scr"
        out: "boot.scr"
        artifacts:
          - "boot.scr"
      - type: mkimage
        exe: "loader/u-boot/tools/mkimage"
        sources:
          - "linux/kernel/arch/arm64/boot/Image"
        out: "linux/kernel/kernel.uimg"
        arch: "arm64"
        os: "linux"
        img_type: "kernel"
        name: "kernel"
        load_addr: 0x40000000
        compression: "none"
        artifacts:
          - "linux/kernel/kernel.uimg"
        deps:
          - "loader/u-boot/tools/mkimage"
          - "linux/kernel/arch/arm64/boot/Image"
    builders:
      - type: image.partition
        file: "boot.img"
        fs: ext4
        size: 256 MB
        content:
          - from: "loader/u-boot/u-boot.bin"
            to: "linux/boot/u-boot.bin"
          - from: "linux/kernel/arch/arm64/boot/Image"
            to: "linux/kernel/kernel"
        artifacts:
          - "boot.img"
        deps:
          - ""

  main:
    active: true
    dir: images
    builders:
      - type: image.drive
        file: "main.img"
        partitions:
          - label: boot
            file: "images/boot.img"            
          - label: data
            size: 1024 MB
            fs: ext4
        artifacts:
          - "main.img"
        deps:
          - ""


