author: "dterletskiy"
version: "1.1.0"
umbs_min_version: "0.1"



variables:
  DIRECTORIES:
    ROOT: "/mnt/dev/tmp/build/"
    SOURCE: ${DIRECTORIES.ROOT}/source/
    BUILD: ${DIRECTORIES.ROOT}/build/
    DEPLOY: ${DIRECTORIES.ROOT}/deploy/
    TEST: ${DIRECTORIES.ROOT}/_____/${DIRECTORIES.SOURCE}/_____/${DIRECTORIES.BUILD}/_____/${DIRECTORIES.DEPLOY}/
  XEN:
    SOURCE:
      GITHUB:
        URL: "https://github.com/xen-project/xen.git"
        BRANCH: "RELEASE-4.16.2"
    CONFIG:
      ARM: defconfig
      ARM64: defconfig
      X86: qemu-defconfig
      X86_64: qemu-defconfig
  UBOOT:
    SOURCE:
      GITHUB:
        URL: "https://github.com/u-boot/u-boot.git"
        BRANCH: "v2022.07"
    CONFIG:
      ARM: qemu_arm_defconfig
      ARM64: qemu_arm64_defconfig
      X86: qemu-x86_defconfig
      X86_64: qemu-x86_64_defconfig
  BUSYBOX:
    SOURCE:
      GITHUB:
        URL: "https://github.com/mirror/busybox.git"
        BRANCH: "1_36_0"
    CONFIG:
      ARM: defconfig
      ARM64: defconfig
      X86: defconfig
      X86_64: defconfig
  BUILDROOT:
    SOURCE:
      GITHUB:
        URL: "https://github.com/buildroot/buildroot.git"
        BRANCH: "2023.02"
    CONFIG:
      ARM: qemu_arm_vexpress_defconfig
      ARM64: qemu_aarch64_virt_defconfig
      X86: qemu_x86_defconfig
      X86_64: qemu_x86_64_defconfig
  KERNEL:
    SOURCE:
      GITHUB:
        URL: "https://github.com/torvalds/linux.git"
        BRANCH: "v6.2"
    CONFIG:
      ARM: vexpress_defconfig
      ARM64: defconfig
      X86: x86_64_defconfig
      X86_64: x86_64_defconfig
  ANDROID:
    UBOOT:
      SOURCE:
        GITHUB:
          URL: "https://github.com/dterletskiy/aosp_manifest.git"
          BRANCH: "u-boot/manifest/u-boot-mainline-9671786"
      CONFIG:
        ARM64: "//u-boot:qemu_aarch64"
    KERNEL:
      SOURCE:
        GITHUB:
          URL: "https://github.com/dterletskiy/aosp_manifest.git"
          BRANCH: "kernel/manifest/common-android14-6.1-dev"
      CONFIG:
        ARM64: "//common-modules/virtual-device:virtual_device_aarch64"



tools:
  mkimage:
    type: mkimage
    exe: "u-boot/tools/mkimage"

projects:
  xen:
    active: true
    dir: xen
    sources:
      - type: git
        url: ${XEN.SOURCE.GITHUB.URL}
        branch: ${XEN.SOURCE.GITHUB.BRANCH}
    builders:
      - type: xen
        defconfig: ${XEN.CONFIG.ARM64}
        arch: "arm64"
        compiler: "aarch64-linux-gnu-"
        compiler_path: "/usr/aarch64-linux-gnu"
        jobs: 4
        targets:
          - "dist-xen"
          - "dist-doc"
        env:
          - ""
        artifacts:
          - "dist/install/boot/xen"
        deps:
          - ""

  u-boot:
    active: true
    dir: u-boot
    sources:
      - type: git
        url: ${UBOOT.SOURCE.GITHUB.URL}
        branch: ${UBOOT.SOURCE.GITHUB.BRANCH}
    builders:
      - type: uboot
        defconfig: ${UBOOT.CONFIG.ARM64}
        arch: "arm64"
        compiler: "aarch64-linux-gnu-"
        compiler_path: "/usr/aarch64-linux-gnu"
        jobs: 4
        env:
          - ""
        artifacts:
          - "u-boot"
          - "u-boot.bin"
          - "scripts/dtc/dtc"
          - "tools/dumpimage"
          - "tools/fit_info"
          - "tools/mkenvimage"
          - "tools/mkimage"
          - "tools/img2srec"
        deps:
          - ""

  busybox:
    active: true
    dir: busybox
    sources:
      - type: git
        url: ${BUSYBOX.SOURCE.GITHUB.URL}
        branch: ${BUSYBOX.SOURCE.GITHUB.BRANCH}
    builders:
      - type: busybox
        defconfig: ${BUSYBOX.CONFIG.ARM64}
        arch: "arm64"
        compiler: "aarch64-linux-gnu-"
        compiler_path: "/usr/aarch64-linux-gnu"
        jobs: 4
        env:
          - ""
        artifacts:
          - "_install"
        deps:
          - ""

  buildroot:
    active: true
    dir: buildroot
    sources:
      - type: git
        url: ${BUILDROOT.SOURCE.GITHUB.URL}
        branch: ${BUILDROOT.SOURCE.GITHUB.BRANCH}
    builders:
      - type: buildroot
        defconfig: ${BUILDROOT.CONFIG.ARM64}
        arch: "arm64"
        compiler: "aarch64-linux-gnu-"
        compiler_path: "/usr/aarch64-linux-gnu"
        jobs: 4
        env:
          - ""
        artifacts:
          - "output/images/rootfs.cpio"
          - "output/images/rootfs.ext2"
        deps:
          - ""

  kernel:
    active: true
    dir: kernel
    sources:
      - type: git
        url: ${KERNEL.SOURCE.GITHUB.URL}
        branch: ${KERNEL.SOURCE.GITHUB.BRANCH}
    builders:
      - type: kernel
        defconfig: ${KERNEL.CONFIG.ARM64}
        arch: "arm64"
        compiler: "aarch64-linux-gnu-"
        compiler_path: "/usr/aarch64-linux-gnu"
        jobs: 4
        env:
          - ""
        artifacts:
          - "arch/arm64/boot/Image"
          - "arch/arm64/boot/Image.gz"
        deps:
          - ""

  android-u-boot:
    active: true
    dir: android/u-boot
    sources:
      - type: repo
        manifest-url: ${ANDROID.UBOOT.SOURCE.GITHUB.URL}
        manifest-branch: ${ANDROID.UBOOT.SOURCE.GITHUB.BRANCH}
        manifest-name: "default.xml"
    builders:
      - type: android.uboot
        config: ${ANDROID.UBOOT.CONFIG.ARM64}
        env:
          - ""
        artifacts:
          - "out/deploy/${ANDROID.UBOOT.CONFIG.ARM64}/u-boot.bin"
        deps:
          - ""

  android-kernel:
    active: true
    dir: android/kernel
    sources:
      - type: repo
        manifest-url: ${ANDROID.KERNEL.SOURCE.GITHUB.URL}
        manifest-branch: ${ANDROID.KERNEL.SOURCE.GITHUB.BRANCH}
        manifest-name: "default.xml"
    builders:
      - type: android.kernel
        config: ${ANDROID.KERNEL.CONFIG.ARM64}
        env:
          - ""
        artifacts:
          - "out/deploy/${ANDROID.UBOOT.CONFIG.ARM64}/u-boot.bin"
        deps:
          - ""

  boot:
    active: true
    dir: images
    builders:
      - type: image.partition
        file: "boot.img"
        fs: ext4
        size: 256 MB
        content:
          - from: "u-boot/u-boot.bin"
            to: "boot/u-boot.bin"
          - from: "kernel/arch/arm64/boot/Image"
            to: "kernel/kernel"
        artifacts:
          - "boot.img"
        deps:
          - ""

  main:
    active: true
    dir: images
    builders:
      - type: image.drive
        file: "main.img"
        partitions:
          - label: boot
            file: "images/boot.img"            
          - label: data
            size: 1024 MB
            fs: ext4
        artifacts:
          - "main.img"
        deps:
          - ""


