docker-image-x64:
  active: true
  subdir: None
  version: ${UBUNTU.VERSION}
  builders:
    - type: docker.image
      dockerfile: ${UBUNTU.DOCKER.DOCKERFILE}
      from:
        name: ubuntu
        tag: ${UBUNTU.VERSION}
      image:
        name: builder/x64/ubuntu
        tag: ${UBUNTU.VERSION}
      user: ${UBUNTU.USER}
      packages:
        apt: ${UBUNTU.PACKAGES.APT}
        pip3: ${UBUNTU.PACKAGES.PIP3}
      container_name: builder_x64_ubuntu_${UBUNTU.VERSION}

docker-image-aarch64:
  active: true
  subdir: None
  builders:
    - type: docker.image
      dockerfile: ${UBUNTU.DOCKER.DOCKERFILE}
      from:
        name: arm64v8/ubuntu
        tag: ${UBUNTU.VERSION}
      image:
        name: builder/arm64v8/ubuntu
        tag: ${UBUNTU.VERSION}
      user: ${UBUNTU.USER}
      packages:
        apt: ${UBUNTU.PACKAGES.APT}
        pip3: ${UBUNTU.PACKAGES.PIP3}
      container_name: builder_arm64v8_ubuntu_${UBUNTU.VERSION}
