  docker-image-aarch64:
    active: true
    project_subdir: None
    builders:
      - type: docker.image
        dockerfile: ${UBUNTU.DOCKER.DOCKERFILE}
        from:
          name: arm64v8/ubuntu
          tag: ${UBUNTU.VERSION}
        image:
          name: builder/arm64v8/ubuntu
          tag: ${UBUNTU.VERSION}
        user: ${UBUNTU.USER}
        packages:
          apt: ${UBUNTU.PACKAGES.APT}
          pip3: ${UBUNTU.PACKAGES.PIP3}
        container_name: builder_arm64v8_ubuntu_${UBUNTU.VERSION}
