  docker-image-x64:
    active: true
    project_subdir: None
    version: ${UBUNTU.VERSION}
    builders:
      - type: docker.image
        dockerfile: ${UBUNTU.DOCKER.DOCKERFILE}
        from:
          name: ubuntu
          tag: ${UBUNTU.VERSION}
        image:
          name: builder/x64/ubuntu
          tag: ${UBUNTU.VERSION}
        user: ${UBUNTU.USER}
        packages:
          apt: ${UBUNTU.PACKAGES.APT}
          pip3: ${UBUNTU.PACKAGES.PIP3}
        container_name: builder_x64_ubuntu_${UBUNTU.VERSION}
