ARG ARG_OS_NAME=ubuntu
ARG ARG_OS_VERSION=20.04

FROM ${ARG_OS_NAME}:${ARG_OS_VERSION}

ARG ARG_MESSAGE_PREFIX="-------------------------// "
ARG ARG_MESSAGE_SUFFIX=" //-------------------------"

# Fix for tzdata for docker image build
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone


# Install necessary for build packages
ARG ARG_APT_PACKAGES=""
RUN PACKAGES=${ARG_APT_PACKAGES}; \
   PACKAGES_COUNT=$(echo "${PACKAGES}" | wc -w); \
   echo "Number of 'apt' packages to be installed: ${PACKAGES_COUNT}"; \
   INSTALLED_PACKAGES=0; \
   for PACKAGE in ${PACKAGES}; do \
      INSTALLED_PACKAGES=$((INSTALLED_PACKAGES + 1)); \
      echo ${ARG_MESSAGE_PREFIX} \
         "Installing 'apt' package (${INSTALLED_PACKAGES}/${PACKAGES_COUNT}): ${PACKAGE}" \
         ${ARG_MESSAGE_SUFFIX}; \
      apt update && apt install -y ${PACKAGE} || true; \
   done


# Install necessary for build packages
ARG ARG_PIP2_PACKAGES=""
RUN PACKAGES=${ARG_PIP2_PACKAGES}; \
   PACKAGES_COUNT=$(echo "${PACKAGES}" | wc -w); \
   echo "Number of 'pip2' packages to be installed: ${PACKAGES_COUNT}"; \
   INSTALLED_PACKAGES=0; \
   for PACKAGE in ${PACKAGES}; do \
      INSTALLED_PACKAGES=$((INSTALLED_PACKAGES + 1)); \
      echo ${ARG_MESSAGE_PREFIX} \
         "Installing 'pip2' package (${INSTALLED_PACKAGES}/${PACKAGES_COUNT}): ${PACKAGE}" \
         ${ARG_MESSAGE_SUFFIX}; \
      pip2 install ${PACKAGE} || true; \
   done


# Install necessary for build packages
ARG ARG_PIP3_PACKAGES=""
RUN PACKAGES=${ARG_PIP3_PACKAGES}; \
   PACKAGES_COUNT=$(echo "${PACKAGES}" | wc -w); \
   echo "Number of 'pip3' packages to be installed: ${PACKAGES_COUNT}"; \
   INSTALLED_PACKAGES=0; \
   for PACKAGE in ${PACKAGES}; do \
      INSTALLED_PACKAGES=$((INSTALLED_PACKAGES + 1)); \
      echo ${ARG_MESSAGE_PREFIX} \
         "Installing 'pip3' package (${INSTALLED_PACKAGES}/${PACKAGES_COUNT}): ${PACKAGE}" \
         ${ARG_MESSAGE_SUFFIX}; \
      pip3 install ${PACKAGE} || true; \
   done


# Define user credentials and data
ARG ARG_USER_NAME=guest
ARG ARG_USER_PASSWORD=
ARG ARG_USER_HASHED_PASSWORD=
ARG ARG_USER_PASSWORD_SALT="guest"
ARG ARG_USER_UID=1000
ARG ARG_USER_GID=1000
ARG ARG_USER_WORKDIR="workspace"

# Creating the user
RUN echo ${ARG_MESSAGE_PREFIX} "Defining user password" ${ARG_MESSAGE_SUFFIX}; \
   if [ -z ${ARG_USER_PASSWORD+x} ] || [ -z ${ARG_USER_PASSWORD} ]; then \
      echo ${ARG_MESSAGE_PREFIX} "User password is unset or empty" ${ARG_MESSAGE_SUFFIX}; \
      echo ${ARG_MESSAGE_PREFIX} "User password will be used as user name" ${ARG_MESSAGE_SUFFIX}; \
      ARG_USER_PASSWORD=${ARG_USER_NAME}; \
   else \
      echo ${ARG_MESSAGE_PREFIX} "User password is set to '${ARG_USER_PASSWORD}'" ${ARG_MESSAGE_SUFFIX}; \
   fi; \
   echo ${ARG_MESSAGE_PREFIX} "User password: '${ARG_USER_PASSWORD}'" ${ARG_MESSAGE_SUFFIX}; \
   \
   if [ -z ${ARG_USER_HASHED_PASSWORD+x} ] || [ -z ${ARG_USER_HASHED_PASSWORD} ]; then \
      echo ${ARG_MESSAGE_PREFIX} "User hashed password is unset or empty" ${ARG_MESSAGE_SUFFIX}; \
      echo ${ARG_MESSAGE_PREFIX} "Generating user hashed password from user password" ${ARG_MESSAGE_SUFFIX}; \
      ARG_USER_HASHED_PASSWORD=$(perl -e "print crypt(${ARG_USER_PASSWORD},${ARG_USER_PASSWORD_SALT})"); \
      ARG_USER_HASHED_PASSWORD=$(mkpasswd -m sha-512 -S ${ARG_USER_PASSWORD_SALT} ${ARG_USER_PASSWORD}); \
   else \
      echo ${ARG_MESSAGE_PREFIX} "User hashed password is set to '${ARG_USER_HASHED_PASSWORD}'" ${ARG_MESSAGE_SUFFIX}; \
   fi; \
   echo ${ARG_MESSAGE_PREFIX} "User hashed password: '${ARG_USER_HASHED_PASSWORD}'" ${ARG_MESSAGE_SUFFIX}; \
   \
   groupadd --gid ${ARG_USER_GID} ${ARG_USER_NAME} && \
   useradd \
      --uid ${ARG_USER_UID} \
      --gid ${ARG_USER_GID} \
      --create-home \
      --shell /bin/bash \
      --groups adm,sudo \
      --password ${ARG_USER_HASHED_PASSWORD} \
      ${ARG_USER_NAME}

# Switch the user from root to ${ARG_USER_NAME}
USER ${ARG_USER_NAME}
ENV USER_NAME=${ARG_USER_NAME}

# Create workdir for docker and define it as WORKDIR
RUN mkdir -p /home/${ARG_USER_NAME}/${ARG_USER_WORKDIR} && \
   chown ${ARG_USER_NAME}:${ARG_USER_NAME} /home/${ARG_USER_NAME}/${ARG_USER_WORKDIR}
ENV BUILD_DIR /home/${ARG_USER_NAME}/${ARG_USER_WORKDIR}
WORKDIR ${BUILD_DIR}
ENV PATH ~/.local/bin:${PATH}
