container:
  ubuntu-aarch64:
    type: docker
    name: builder_arm64v8_ubuntu_${UBUNTU.VERSION}
    disposable: true
    image:
      name: builder/arm64v8/ubuntu
      tag: ${UBUNTU.VERSION}
    mapping:
      volume:
        - host: ${DIRECTORIES.ROOT}
          guest: ${DIRECTORIES.CONTAINER.ROOT}
        - host: ~/.ssh
          guest: /home/${UBUNTU.USER.NAME}/.ssh
        - host: ~/.gitconfig
          guest: /home/${UBUNTU.USER.NAME}/.gitconfig
      port:
        - host: 5000
          guest: 5000
